include /srv/www/sqlinjection.cz/conf/nginx/common-https.conf;
ssl_certificate /etc/letsencrypt/live/sqlinjection.rocks/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/sqlinjection.rocks/privkey.pem;

ssl_stapling on;
resolver 8.8.8.8 8.8.4.4;
